---
- hosts: all

  vars_prompt:
    - name: "USER"
      prompt: "Enter USER name"
      private: no

  tasks:
    - name: generate new password
      shell: /usr/bin/pwgen 10 -c1
      register: PASS

    - name: save password in file /root/user_password.txt
      shell: echo "{{USER}}" > /root/user_password.txt; echo "{{PASS.stdout}}" >> /root/user_password.txt

    - name: set password
      shell: echo -e "{{PASS.stdout}}\n{{PASS.stdout}}" | (passwd --stdin "{{USER}}")
