---
- name: Transfer and execute a script.
  hosts: test
  user: root
  #sudo: yes
  tasks:
     - name: Transfer the script
       copy: src=test.sh dest=/root mode=0777

     - name: Execute the script
       local_action: command bash /home/test_user/test.sh
