---
- name: Transfer and execute a script.
  hosts: test
  user: root
  #sudo: yes
  tasks:
     - name: Transfer the script
       copy: src=test.sh dest=/root mode=0744

     - name: Execute the script
       command: bash /root/test.sh
